# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 401, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.lblForce = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblForce.setObjectName("lblForce")
        self.gridLayout.addWidget(self.lblForce, 1, 0, 1, 1)
        self.lblInletDuty = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblInletDuty.setObjectName("lblInletDuty")
        self.gridLayout.addWidget(self.lblInletDuty, 2, 0, 1, 1)
        self.lblOutletDuty = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblOutletDuty.setObjectName("lblOutletDuty")
        self.gridLayout.addWidget(self.lblOutletDuty, 3, 0, 1, 1)
        self.lblRpm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblRpm.setObjectName("lblRpm")
        self.gridLayout.addWidget(self.lblRpm, 0, 0, 1, 1)
        self.lcdForce = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdForce.setObjectName("lcdForce")
        self.gridLayout.addWidget(self.lcdForce, 1, 1, 1, 1)
        self.lcdInletDuty = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdInletDuty.setObjectName("lcdInletDuty")
        self.gridLayout.addWidget(self.lcdInletDuty, 2, 1, 1, 1)
        self.lcdOutletDuty = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdOutletDuty.setObjectName("lcdOutletDuty")
        self.gridLayout.addWidget(self.lcdOutletDuty, 3, 1, 1, 1)
        self.lcdRpm = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdRpm.setObjectName("lcdRpm")
        self.gridLayout.addWidget(self.lcdRpm, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionCalibration = QtWidgets.QAction(MainWindow)
        self.actionCalibration.setObjectName("actionCalibration")
        self.actionSteady_State = QtWidgets.QAction(MainWindow)
        self.actionSteady_State.setObjectName("actionSteady_State")
        self.actionRamping = QtWidgets.QAction(MainWindow)
        self.actionRamping.setObjectName("actionRamping")
        self.actionRoad_Simulation = QtWidgets.QAction(MainWindow)
        self.actionRoad_Simulation.setObjectName("actionRoad_Simulation")
        self.actionSerial_Port = QtWidgets.QAction(MainWindow)
        self.actionSerial_Port.setObjectName("actionSerial_Port")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblForce.setText(_translate("MainWindow", "Load Cell Force"))
        self.lblInletDuty.setText(_translate("MainWindow", "Inlet Valve Duty Cycle"))
        self.lblOutletDuty.setText(_translate("MainWindow", "Outlet Valve Duty Cycle"))
        self.lblRpm.setText(_translate("MainWindow", "Shaft RPM"))
        self.actionCalibration.setText(_translate("MainWindow", "Calibration"))
        self.actionSteady_State.setText(_translate("MainWindow", "Steady State"))
        self.actionRamping.setText(_translate("MainWindow", "Ramping"))
        self.actionRoad_Simulation.setText(_translate("MainWindow", "Road Simulation"))
        self.actionSerial_Port.setText(_translate("MainWindow", "Serial Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
